---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: oauth-secrets
        secret:
          secretName: oauth2
          items:
          - key: client-secret.json
            path: client-secret.json
      containers:
      - name: web
        image: gcr.io/ahmetb-starter/web:latest
        imagePullPolicy: IfNotPresent # minikube-only
        args:
        - "-addr=:8000"
        - "-google-oauth2-config=/etc/secrets/client-secret.json"
        - "-user-directory-addr=userdirectory.default:80"
        - "-coffee-directory-addr=coffeedirectory.default:80"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: oauth-secrets
          mountPath: /etc/secrets
          readOnly: true
        resources:
          requests:
            cpu: 100mi
            memory: 64Mi
          limits:
            cpu: 300mi
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userdirectory-deployment
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: userdirectory
    spec:
      volumes:
      - name: oauth-secrets
        secret:
          secretName: google-service-account
          items:
          - key: app_default_credentials.json
            path: app-credentials.json
      containers:
      - name: userdirectory
        image: gcr.io/ahmetb-starter/userdirectory:latest
        args:
        - "-addr=:8001"
        - "-google-project-id=ahmetb-starter"
        imagePullPolicy: IfNotPresent # minikube-only
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: oauth-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/app-credentials.json
        resources:
          requests:
            cpu: 100mi
            memory: 64Mi
          limits:
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffeedirectory-deployment
spec:
  revisionHistoryLimit: 5
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: coffeedirectory
    spec:
      volumes:
      - name: oauth-secrets
        secret:
          secretName: google-service-account
          items:
          - key: app_default_credentials.json
            path: app-credentials.json
      containers:
      - name: coffeedirectory
        image: gcr.io/ahmetb-starter/coffeedirectory:latest
        imagePullPolicy: IfNotPresent # minikube-only
        args:
        - "-addr=:8002"
        - "-user-directory-addr=userdirectory.default:80"
        - "-google-project-id=ahmetb-starter"
        ports:
        - containerPort: 8002
        volumeMounts:
        - name: oauth-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/app-credentials.json
        resources:
          requests:
            cpu: 100mi
            memory: 64Mi
          limits:
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8002
