---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: oauth-secrets
        secret:
          secretName: oauth2
          items:
          - key: client-secret.json
            path: client-secret.json
      containers:
      - name: web
        image: gcr.io/ahmetb-starter/monoimage:latest
        imagePullPolicy: IfNotPresent # minikube-only
        command: ["web"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: oauth-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: GOOGLE_OAUTH2_CONFIG
          value: /etc/secrets/client-secret.json
        - name: USER_DIRECTORY_HOST
          value: userdirectory.default:80
        - name: COFFEE_DIRECTORY_HOST
          value: coffeedirectory.default:80
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userdirectory-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: userdirectory
    spec:
      volumes:
      - name: oauth-secrets
        secret:
          secretName: google-service-account
          items:
          - key: app_default_credentials.json
            path: app-credentials.json
      containers:
      - name: userdirectory
        image: gcr.io/ahmetb-starter/monoimage:latest
        command: ["userdirectory"]
        imagePullPolicy: IfNotPresent # minikube-only
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: oauth-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/app-credentials.json
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffeedirectory-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: coffeedirectory
    spec:
      volumes:
      - name: oauth-secrets
        secret:
          secretName: google-service-account
          items:
          - key: app_default_credentials.json
            path: app-credentials.json
      containers:
      - name: coffeedirectory
        image: gcr.io/ahmetb-starter/monoimage:latest
        imagePullPolicy: IfNotPresent # minikube-only
        command: ["coffeedirectory"]
        ports:
        - containerPort: 8002
        volumeMounts:
        - name: oauth-secrets
          mountPath: /etc/secrets
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/app-credentials.json
        - name: USER_DIRECTORY_HOST
          value: userdirectory.default:80
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8002
